name: pgl-cnv-analysis
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  # =======================================================
  # CORE
  # =======================================================
  - python=3.9

  # =======================================================
  # BIOINFORMATICS
  # =======================================================
  - samtools
  - tabix
  - picard
  - pysam
  - biopython

  # =======================================================
  # SCIENTIFIC STACK
  # =======================================================
  # Pandas < 2.0 mandatory for CNVkit 0.9.10
  - pandas<2.0
  # Numpy < 2.0 mandatory for CNVkit 0.9.10, 1.26.4 is the last stable version before 2.0
  - numpy>=1.22,<2.0
  - scipy
  - matplotlib-base
  - seaborn
  - scikit-learn
  - reportlab
  - pomegranate

  # =======================================================
  # UTILITIES
  # =======================================================
  - pip
  - wget

  # =======================================================
  # PIP
  # =======================================================
  - pip:
    # Forced numpy version to avoid update from sigprofilermatrixgenerator
    - numpy<2.0 
    - SigProfilerMatrixGenerator
